# Generated by Django 6.1.1 on 2026-09-11 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('risk_score__gte', 0), ('risk_score__lte', 100)), name='risk_score_between_0_and_100'),
        ),
    ]
