# Generated by Django 6.1.1 on 2026-09-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_risk_score_between_0_and_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='risk_weight',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
