# Generated by Django 6.1.1 on 2026-09-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_category_risk_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20),
        ),
    ]
