# Generated by Django 6.1.1 on 2026-09-16 21:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_reportcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
